# This workflow will build geo-11 for Release use, but is specifically set
# up to build the HelixMod version.
# This is a basic workflow that will only be manually triggered, but will
# call through to the main Release workflow.

name: HelixMod Manual Build

# Controls when the action will run. Workflow runs when manually triggered using the UI.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Create a Release build for HelixMod use'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

# This is a copy of the msbuild.yml action script. The setup to
# call out to another job is too restrictive, so let's just duplicate
# the sequence, but upload different artifact here.

jobs:
  zip_release_workflow:

    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout vs2022
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Add MSBuild for vs2022 to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '[17,)'


#    - name: Setup NuGet.exe for use with actions
#      uses: NuGet/setup-nuget@v1.0.6
#    - name: Restore nuget packages
#      run: nuget restore StereovisionHacks.sln

    - name: Build via Publish.bat
      shell: cmd
      run: call .\Publish.bat 

# In order to pass the version number from the Publish.bat script back here to Actions,
# we need to fetch it using powershell commands. Normal echo and cat don't work here.
# Fetches the version from the embedded version file name.
# It's also worth noting that the env.GITHUB_ENV is only read at the start of a Step,
# so the variable will be wrong until the next step.

    - name: Get Version
      id: get-version
      shell: pwsh
      run: |
        # Verify path exists
        $versionPath = ".\Zip Release"
        if (-not (Test-Path $versionPath)) {
            throw "Error: Path '$versionPath' not found"
        }
        
        # Find version file
        $versionFile = Get-ChildItem -Path $versionPath -Filter "Version-*" | Select-Object -First 1
        if ($null -eq $versionFile) {
            throw "Error: No Version-* file found in '$versionPath'"
        }
        
        # Read version
        $version = Get-Content $versionFile.FullName -Raw
        if ([string]::IsNullOrWhiteSpace($version)) {
            throw "Error: Version file is empty"
        }
        
        # Clean version string and set
        $version = $version.Trim()
        "BUILD_VERSION=$version" >> $env:GITHUB_ENV
        Write-Host "Version detected: $version"
# Add a new commit for the bump in version number.        
# We add the git pull --ff 

    - name: Commit version change
      if: env.BUILD_VERSION != ''
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull --ff-only origin ${{ github.ref }}
        git commit -am "CI Build - ${{env.BUILD_VERSION}}"
        git push
        
# Now we can upload the remaining artifacts as the HelixMod version.

    - name: Upload HelixMod build
      if: env.BUILD_VERSION != ''
      uses: actions/upload-artifact@v4
      with:
        name: 3Dmigoto v${{env.BUILD_VERSION}}
        path: Zip Release\
        compression-level: 9  # Maximum compression to reduce artifact size
        retention-days: 90
